### ISSUE TITLE
Error after running githook

### ISSUE THREAD

**Issue by joeworkman** [greenpau/caddy-git#8]
**Describe the issue**

When processing the githook, I am getting the following error.

```
Jan 14 16:14:28 nycaddy caddy[192921]: {"level":"warn","ts":1642194868.222069,"logger":"http.handlers.git","msg":"failed updating repo","repo_name":"aspecthq.com","error":"object not found"}
```

**Configuration**

Paste full `Caddyfile` below:

```
{
    git {
        repo aspecthq.com {
            base_dir /var/www
            url https://gitlab.com/joeworkman/aspecthq.com.git
            branch master
            depth 1
            # auth ssh /var/www/ssh/id_rsa.pub
            webhook name X-Gitlab-Token go-caddy-git-go
            # post pull exec {
            #     name Pager
            #     command /usr/local/bin/pager
            #     args "pulled authp.github.io repo"
            # }
        }
    }
}
aspecthq.com {
    redir https://www.aspecthq.com{uri}
}
www.aspecthq.com {
    log {
        output file /var/log/caddy/aspecthq.com/access.log {
            roll_size 3MiB
            roll_keep 5
            roll_keep_for 48h
        }
    }
    handle_errors {
        respond "{http.error.status_code} {http.error.status_text}"
        # rewrite * /{http.error.status_code}.html
        # file_server
    }
    route /update {
        git update repo aspecthq.com
    }
    encode gzip zstd
    php_fastcgi unix//run/php/php8.1-fpm.sock
    file_server
    root * /var/www/aspecthq.com
    push
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep git` below:

```
git v1.0.4
http.handlers.git v1.0.4
```

**Expected behavior**

I would expect a pull request to be made

**Additional context**

https://github.com/greenpau/caddy-git/issues/1#issuecomment-1013469973

**Comment by greenpau** [comment]
What is in .git/config?

**Comment by joeworkman** [comment]
```
[core]
	bare = false
[remote "origin"]
	url = https://gitlab.com/joeworkman/aspecthq.com.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by greenpau** [comment]
@joeworkman , does the same happen with github repos?

**Comment by greenpau** [comment]
@joeworkman , also, what is the OS running caddy?

**Comment by joeworkman** [comment]
The server is Ubuntu 20. I can test a Github repo. Maybe not tonight though.

**Comment by joeworkman** [comment]
Here is the config from Github. 

```
[core]
	bare = false
[remote "origin"]
	url = https://github.com/joeworkman/aspecthq.com.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

Looks pretty much the same minus the URL.

**Comment by joeworkman** [comment]
I am also getting the object not found with Github where the repo has already been cloned. However, if I delete the repo from the server and restart caddy, it does get created and Caddy does start.

**Comment by joeworkman** [comment]
Does this work for you locally on your computer? Do you have an example that works?

**Comment by greenpau** [comment]
Yes, it does. Do you have anything special in you .gitconfig?

**Comment by greenpau** [comment]
@joeworkman , all the examples in config directory work for me, e.g. https://github.com/greenpau/caddy-git/blob/main/assets/config/Caddyfile

also, as part of the test harness, I do git clone and then git pull.

**Comment by joeworkman** [comment]
I have simplified my config down to.... 

```
{
    git {
        repo aspecthq.com {
            base_dir /var/www/aspecthq.com
            url https://github.com/joeworkman/aspecthq.com.git
            branch master
            depth 1
        }
    }
}
aspecthq.com {
    redir https://www.aspecthq.com{uri}
}
www.aspecthq.com {
    route /update {
        git update repo aspecthq.com
    }
    encode gzip zstd
    php_fastcgi unix//run/php/php8.1-fpm.sock
    root * /var/www/aspecthq.com/aspecthq.com
    file_server
    push
}
```

I enabled debugging and got the following errors in the logs. Does this help?

```
Jan 17 23:57:15 nycaddy caddy[50249]: {"level":"debug","ts":1642481835.4307551,"logger":"tls.handshake","msg":"matched certificate in cache","subjects":["www.aspecthq.com"],"managed":true,"expiration":1649141617,"hash":"29a9c211883cb7b204d520dc16d7b79a4fc273a96f1d7fd4505c3ad3b93c9d32"}
Jan 17 23:57:15 nycaddy caddy[50249]: {"level":"debug","ts":1642481835.4329338,"logger":"http.handlers.git","msg":"received update git repo request","repo_name":"aspecthq.com"}
Jan 17 23:57:15 nycaddy caddy[50249]: {"level":"warn","ts":1642481835.476297,"logger":"http.handlers.git","msg":"failed updating repo","repo_name":"aspecthq.com","error":"object not found"}
Jan 17 23:58:15 nycaddy caddy[50249]: {"level":"debug","ts":1642481895.211445,"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"67.205.153.109"}
Jan 17 23:58:15 nycaddy caddy[50249]: {"level":"debug","ts":1642481895.2115004,"logger":"tls.handshake","msg":"no certificate matching TLS ClientHello","server_name":"","remote":"91.207.239.70:11520","identifier":"67.205.153.109","cipher_suites":[49200,49196,49192,49188,49172,49162,165,163,161,159,107,106,105,104,57,56,55,54,49202,49198,49194,49190,49167,49157,157,61,53,136,135,134,133,132,49199,49195,49191,49187,49171,49161,164,162,160,158,103,64,63,62,51,50,49,48,49201,49197,49193,49189,49166,49156,156,60,47,154,153,152,151,69,68,67,66,150,65,7,49169,49159,49164,49154,5,4,49170,49160,22,19,16,13,49165,49155,10,255],"cert_cache_fill":0.0004,"load_if_necessary":true,"obtain_if_necessary":true,"on_demand":false}
Jan 17 23:58:15 nycaddy caddy[50249]: {"level":"debug","ts":1642481895.211616,"logger":"http.stdlib","msg":"http: TLS handshake error from 91.207.239.70:11520: no certificate available for '67.205.153.109'"}
```

**Comment by joeworkman** [comment]
I order to get the site up and working, I always need to delete the git repo from the server. Then start Caddy. If the repo exists before Caddy starts, the `object not found` error happens and addy will not start.

**Comment by greenpau** [comment]
@joeworkman , will try finding time later in the week to figure it out.

**Comment by joeworkman** [comment]
Thanks. I'm open to hoping on zoom if that works for you. https://joeworkman.net/bookme

**Comment by greenpau** [comment]
@joeworkman , replied on linkedin

**Comment by love4taylor** [comment]
Any updates? I'm also having this problem

**Comment by greenpau** [comment]
@love4taylor , please enable trace and paste logs from the transaction.

**Comment by love4taylor** [comment]
@greenpau 

```
love4taylor@EGOIST:/data/docker/web$ docker exec -it caddy caddy list-modules -versions | grep git
git v1.0.4
http.handlers.git v1.0.4
```

Reproduction steps.

1. Use the following Caddyfile with an empty /tmp directory for the first clone by caddy-git.

```
{
  debug
  local_certs
  http_port 8081
  https_port 8082
  git {
    repo love4taylor-ruleset {
      base_dir /tmp
      url git@github.com:love4taylor/ruleset.git
      auth key /data/caddy/ssh/love4taylor-ruleset-at-github no_strict_host_key_check
      branch master
      depth 1
    }
  }
}

127.0.0.1, localhost {
  route /update/love4taylor-ruleset {
    git update repo love4taylor-ruleset
  }
  route {
    file_server {
      root /tmp/love4taylor-ruleset
    }
  }
}
```

```
love4taylor@EGOIST:/data/docker/web$ docker exec -it caddy ls /tmp
love4taylor-ruleset
love4taylor@EGOIST:/data/docker/web$ docker exec -it caddy cat /tmp/love4taylor-ruleset/.git/config
[core]
	bare = false
[remote "origin"]
	url = git@github.com:love4taylor/ruleset.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

2. Visit the update link and get a result with 200.

```
love4taylor@EGOIST:/data/docker/web$ curl -k https://localhost:8082/update/love4taylor-ruleset 
{"status_code":200}
```

3. Edit a random file on the GitHub page to update the repository.

4. If you visit the update link again, you will get a 500 error.

```
love4taylor@EGOIST:/data/docker/web$ curl -k https://localhost:8082/update/love4taylor-ruleset 
{"status_code":500}
```

Caddy log:

```
{"level":"info","ts":1645317281.9945788,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1645317281.9958227,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
{"level":"info","ts":1645317282.00131,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1645317282.001372,"logger":"git","msg":"provisioning app instance","app":"git"}
{"level":"debug","ts":1645317285.2619414,"logger":"git","msg":"repo is already up to date","repo_name":"love4taylor-ruleset"}
{"level":"debug","ts":1645317285.2619793,"logger":"git","msg":"registered and synced repo","repo_name":"love4taylor-ruleset"}
{"level":"info","ts":1645317285.2619848,"logger":"git","msg":"provisioned app instance","app":"git"}
{"level":"info","ts":1645317285.262361,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000444380"}
{"level":"info","ts":1645317285.3132598,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":8082}
{"level":"info","ts":1645317285.3132977,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1645317285.3135202,"logger":"http.handlers.git","msg":"provisioned plugin instance","instance_name":"git-love4taylor-ruleset","started_at":1645317285.3135188}
{"level":"info","ts":1645317285.3135424,"logger":"http.handlers.git","msg":"validated plugin instance","instance_name":"git-love4taylor-ruleset"}
{"level":"warn","ts":1645317285.3289602,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}
2022/02/20 00:34:45 Warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again
2022/02/20 00:34:45 define JAVA_HOME environment variable to use the Java trust
{"level":"error","ts":1645317285.345407,"logger":"pki.ca.local","msg":"failed to install root certificate","error":"failed to execute tee: exit status 1","certificate_file":"storage:pki/authorities/local/root.crt"}
{"level":"info","ts":1645317285.3455324,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"debug","ts":1645317285.3456984,"logger":"http","msg":"starting server loop","address":"[::]:8082","http3":false,"tls":true}
{"level":"debug","ts":1645317285.3457665,"logger":"http","msg":"starting server loop","address":"[::]:8081","http3":false,"tls":false}
{"level":"info","ts":1645317285.3457866,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["127.0.0.1","localhost"]}
{"level":"debug","ts":1645317285.346434,"logger":"git","msg":"starting git repo manager","app":"git"}
{"level":"debug","ts":1645317285.3464844,"logger":"git","msg":"started git repo manager","app":"git"}
{"level":"info","ts":1645317285.346653,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1645317285.3467133,"msg":"serving initial configuration"}
{"level":"info","ts":1645317285.3469188,"logger":"tls.obtain","msg":"acquiring lock","identifier":"127.0.0.1"}
{"level":"info","ts":1645317285.34709,"logger":"tls.obtain","msg":"acquiring lock","identifier":"localhost"}
{"level":"info","ts":1645317285.3486009,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1645317285.3653588,"logger":"tls.obtain","msg":"lock acquired","identifier":"127.0.0.1"}
{"level":"info","ts":1645317285.3653681,"logger":"tls.obtain","msg":"lock acquired","identifier":"localhost"}
{"level":"debug","ts":1645317285.3658006,"logger":"tls.obtain","msg":"trying issuer 1/1","issuer":"local"}
{"level":"debug","ts":1645317285.3659308,"logger":"tls.obtain","msg":"trying issuer 1/1","issuer":"local"}
{"level":"info","ts":1645317285.3667057,"logger":"tls.obtain","msg":"certificate obtained successfully","identifier":"127.0.0.1"}
{"level":"info","ts":1645317285.3667252,"logger":"tls.obtain","msg":"releasing lock","identifier":"127.0.0.1"}
{"level":"info","ts":1645317285.3668232,"logger":"tls.obtain","msg":"certificate obtained successfully","identifier":"localhost"}
{"level":"info","ts":1645317285.3668592,"logger":"tls.obtain","msg":"releasing lock","identifier":"localhost"}
{"level":"warn","ts":1645317285.3670905,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [127.0.0.1]: no OCSP server specified in certificate"}
{"level":"debug","ts":1645317285.3671472,"logger":"tls.cache","msg":"added certificate to cache","subjects":["127.0.0.1"],"expiration":1645360485,"managed":true,"issuer_key":"local","hash":"ee0587353a6020ec79a0c9a158ae579572433c131373fe69c1cf659dee39f82f","cache_size":1,"cache_capacity":10000}
{"level":"warn","ts":1645317285.3673387,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [localhost]: no OCSP server specified in certificate"}
{"level":"debug","ts":1645317285.367362,"logger":"tls.cache","msg":"added certificate to cache","subjects":["localhost"],"expiration":1645360485,"managed":true,"issuer_key":"local","hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a","cache_size":2,"cache_capacity":10000}
{"level":"debug","ts":1645317488.2705314,"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"172.22.233.233"}
{"level":"debug","ts":1645317488.270603,"logger":"tls.handshake","msg":"no certificate matching TLS ClientHello","server_name":"","remote":"172.22.0.1:38272","identifier":"172.22.233.233","cipher_suites":[4866,4867,4865,49196,49200,159,52393,52392,52394,49195,49199,158,49188,49192,107,49187,49191,103,49162,49172,57,49161,49171,51,157,156,61,60,53,47,255],"cert_cache_fill":0.0002,"load_if_necessary":true,"obtain_if_necessary":true,"on_demand":false}
{"level":"debug","ts":1645317488.2706978,"logger":"http.stdlib","msg":"http: TLS handshake error from 172.22.0.1:38272: no certificate available for '172.22.233.233'"}
{"level":"debug","ts":1645317495.3779979,"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"172.22.233.233"}
{"level":"debug","ts":1645317495.3780327,"logger":"tls.handshake","msg":"no certificate matching TLS ClientHello","server_name":"","remote":"172.22.0.1:38294","identifier":"172.22.233.233","cipher_suites":[4866,4867,4865,49196,49200,159,52393,52392,52394,49195,49199,158,49188,49192,107,49187,49191,103,49162,49172,57,49161,49171,51,157,156,61,60,53,47,255],"cert_cache_fill":0.0002,"load_if_necessary":true,"obtain_if_necessary":true,"on_demand":false}
{"level":"debug","ts":1645317495.378101,"logger":"http.stdlib","msg":"http: TLS handshake error from 172.22.0.1:38294: no certificate available for '172.22.233.233'"}
{"level":"debug","ts":1645317503.8497517,"logger":"tls.handshake","msg":"choosing certificate","identifier":"localhost","num_choices":1}
{"level":"debug","ts":1645317503.8498013,"logger":"tls.handshake","msg":"default certificate selection results","identifier":"localhost","subjects":["localhost"],"managed":true,"issuer_key":"local","hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a"}
{"level":"debug","ts":1645317503.8498123,"logger":"tls.handshake","msg":"matched certificate in cache","subjects":["localhost"],"managed":true,"expiration":1645360485,"hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a"}
{"level":"debug","ts":1645317503.851655,"logger":"http.handlers.git","msg":"received update git repo request","repo_name":"love4taylor-ruleset"}
{"level":"debug","ts":1645317505.2986476,"logger":"git","msg":"repo is already up to date","repo_name":"love4taylor-ruleset"}
{"level":"info","ts":1645317534.7956712,"msg":"shutting down apps, then terminating","signal":"SIGTERM"}
{"level":"warn","ts":1645317534.7957308,"msg":"exiting; byeee!! 👋","signal":"SIGTERM"}
{"level":"debug","ts":1645317534.7957864,"logger":"git","msg":"stopping git repo manager","app":"git"}
{"level":"debug","ts":1645317534.7958012,"logger":"git","msg":"stopped git repo manager","app":"git"}
{"level":"info","ts":1645317534.7986774,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000444380"}
{"level":"info","ts":1645317534.799908,"logger":"admin","msg":"stopped previous server","address":"tcp/localhost:2019"}
{"level":"info","ts":1645317534.7999356,"msg":"shutdown complete","signal":"SIGTERM","exit_code":0}
{"level":"info","ts":1645317535.7761204,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1645317535.7772198,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
{"level":"info","ts":1645317535.7782493,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1645317535.7784822,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000290af0"}
{"level":"info","ts":1645317535.7802722,"logger":"git","msg":"provisioning app instance","app":"git"}
{"level":"debug","ts":1645317537.222351,"logger":"git","msg":"repo is already up to date","repo_name":"love4taylor-ruleset"}
{"level":"debug","ts":1645317537.2223997,"logger":"git","msg":"registered and synced repo","repo_name":"love4taylor-ruleset"}
{"level":"info","ts":1645317537.2224054,"logger":"git","msg":"provisioned app instance","app":"git"}
{"level":"info","ts":1645317537.2225065,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":8082}
{"level":"info","ts":1645317537.2225287,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1645317537.2227457,"logger":"http.handlers.git","msg":"provisioned plugin instance","instance_name":"git-love4taylor-ruleset","started_at":1645317537.2227442}
{"level":"info","ts":1645317537.2227683,"logger":"http.handlers.git","msg":"validated plugin instance","instance_name":"git-love4taylor-ruleset"}
{"level":"warn","ts":1645317537.2388208,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}
2022/02/20 00:38:57 define JAVA_HOME environment variable to use the Java trust
2022/02/20 00:38:57 Warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again
{"level":"error","ts":1645317537.2409725,"logger":"pki.ca.local","msg":"failed to install root certificate","error":"failed to execute tee: exit status 1","certificate_file":"storage:pki/authorities/local/root.crt"}
{"level":"debug","ts":1645317537.2410312,"logger":"git","msg":"starting git repo manager","app":"git"}
{"level":"debug","ts":1645317537.2410405,"logger":"git","msg":"started git repo manager","app":"git"}
{"level":"info","ts":1645317537.2411504,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"debug","ts":1645317537.2412264,"logger":"http","msg":"starting server loop","address":"[::]:8082","http3":false,"tls":true}
{"level":"debug","ts":1645317537.2412918,"logger":"http","msg":"starting server loop","address":"[::]:8081","http3":false,"tls":false}
{"level":"info","ts":1645317537.2413104,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["127.0.0.1","localhost"]}
{"level":"warn","ts":1645317537.2423644,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [127.0.0.1]: no OCSP server specified in certificate"}
{"level":"debug","ts":1645317537.2423923,"logger":"tls.cache","msg":"added certificate to cache","subjects":["127.0.0.1"],"expiration":1645360485,"managed":true,"issuer_key":"local","hash":"ee0587353a6020ec79a0c9a158ae579572433c131373fe69c1cf659dee39f82f","cache_size":1,"cache_capacity":10000}
{"level":"warn","ts":1645317537.2432933,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [localhost]: no OCSP server specified in certificate"}
{"level":"debug","ts":1645317537.243319,"logger":"tls.cache","msg":"added certificate to cache","subjects":["localhost"],"expiration":1645360485,"managed":true,"issuer_key":"local","hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a","cache_size":2,"cache_capacity":10000}
{"level":"info","ts":1645317537.243426,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1645317537.2434363,"msg":"serving initial configuration"}
{"level":"info","ts":1645317537.2550898,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"debug","ts":1645317565.6120722,"logger":"tls.handshake","msg":"choosing certificate","identifier":"localhost","num_choices":1}
{"level":"debug","ts":1645317565.6121302,"logger":"tls.handshake","msg":"default certificate selection results","identifier":"localhost","subjects":["localhost"],"managed":true,"issuer_key":"local","hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a"}
{"level":"debug","ts":1645317565.612141,"logger":"tls.handshake","msg":"matched certificate in cache","subjects":["localhost"],"managed":true,"expiration":1645360485,"hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a"}
{"level":"debug","ts":1645317565.613072,"logger":"http.stdlib","msg":"http: TLS handshake error from 172.22.0.1:38402: local error: tls: bad record MAC"}
{"level":"debug","ts":1645317575.300677,"logger":"tls.handshake","msg":"choosing certificate","identifier":"localhost","num_choices":1}
{"level":"debug","ts":1645317575.3007228,"logger":"tls.handshake","msg":"default certificate selection results","identifier":"localhost","subjects":["localhost"],"managed":true,"issuer_key":"local","hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a"}
{"level":"debug","ts":1645317575.3007333,"logger":"tls.handshake","msg":"matched certificate in cache","subjects":["localhost"],"managed":true,"expiration":1645360485,"hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a"}
{"level":"debug","ts":1645317575.3027444,"logger":"http.handlers.git","msg":"received update git repo request","repo_name":"love4taylor-ruleset"}
{"level":"debug","ts":1645317576.882386,"logger":"git","msg":"repo is already up to date","repo_name":"love4taylor-ruleset"}
{"level":"debug","ts":1645317649.3147297,"logger":"tls.handshake","msg":"choosing certificate","identifier":"localhost","num_choices":1}
{"level":"debug","ts":1645317649.3147724,"logger":"tls.handshake","msg":"default certificate selection results","identifier":"localhost","subjects":["localhost"],"managed":true,"issuer_key":"local","hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a"}
{"level":"debug","ts":1645317649.3147976,"logger":"tls.handshake","msg":"matched certificate in cache","subjects":["localhost"],"managed":true,"expiration":1645360485,"hash":"dfd3b798e2ca76f36ee588eb77233bb9948662607614da1ce7c286072c3ad85a"}
{"level":"debug","ts":1645317649.3167217,"logger":"http.handlers.git","msg":"received update git repo request","repo_name":"love4taylor-ruleset"}
{"level":"warn","ts":1645317650.73021,"logger":"http.handlers.git","msg":"failed updating repo","repo_name":"love4taylor-ruleset","error":"object not found"}
```

**Comment by love4taylor** [comment]
hmmmm, I just tried by removing `depth 1` which solved my problem, It will no longer prompt `object not found`, and will not report error 500.

**Comment by greenpau** [comment]
@love4taylor , there is a bug in the upstream repo related to the depth. I opened an issue about it. Will follow up on it.

once you removed depth, you got it working fine, correct?

**Comment by love4taylor** [comment]
Yes, it works fine after removing the depth. I've pushed a few commits on GitHub, and the webhook is returning 200 and caddy-git is pulling the latest commits correctly.

**Comment by joeworkman** [comment]
So sadly I removed the `depth` config setting and am still getting the the `object not found` error. 

Here is my config... 

```json
{
    debug
    email joe@workmanmail.com
    acme_dns cloudflare JQCVL2k9w2ysylB-_pNmRMTuInVYEg9QBOoAmixG
    git {
        repo aspecthq.com {
            base_dir /var/www/aspecthq.com
            url https://github.com/joeworkman/aspecthq.com.git
            branch master
        }
    }

}
aspecthq.com {
    redir https://www.aspecthq.com{uri}
}
www.aspecthq.com {
    route /update {
        git update repo aspecthq.com
    }
    encode gzip zstd
    php_fastcgi unix//run/php/php8.1-fpm.sock
    root * /var/www/aspecthq.com/aspecthq.com
    file_server
    push
}
```

**Comment by joeworkman** [comment]
Everything seems to be working now that I removed the repo from the server and let the plugin clone it. I can restart caddy and things are working. Hooks are doing there thing. 

Now time to see if I can get it working on a private repo again.
